name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 180
    strategy:
      matrix:
        platform:
          - os-name: MacOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          
          - os-name: MacOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            
          - os-name: Linux-x86_64
            runs-on: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - os-name: Linux-aarch64
            runs-on: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu	
   
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Shared Library
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
    
    env:
      V8_FROM_SOURCE: true
      CARGO_VARIANT_FLAG: ${{ matrix.config.variant == 'release' && '--release' || '' }}
      CARGO_FEATURE_FLAGS: ${{ matrix.config.v8_enable_pointer_compression && '--features v8_enable_pointer_compression' || '' }}
      LIB_NAME: ${{ contains(matrix.config.target, 'windows') && 'rusty_v8' || 'librusty_v8' }}
      LIB_EXT: ${{ contains(matrix.config.target, 'windows') && 'lib' || 'a' }}
      FEATURES_SUFFIX: ${{ matrix.config.v8_enable_pointer_compression && '_ptrcomp' || '' }}
      RUSTFLAGS: -D warnings